[colors]
background = '#0c0c1b8e'
black = '#0c0c1b'
blue = '#AE5672'
cursor = '#c2c2c6'
cyan = '#CA596B'
foreground = '#c2c2c6'
green = '#E16370'
magenta = '#FA857A'
red = '#BA6D85'
tabs = '#c2c2c6'
tabs-active = '#E77084'
white = '#c2c2c6'
yellow = '#c2c2c6'
dim-black = '#0c0c1b8e'
dim-blue = '#AE56728e'
dim-cyan = '#CA596B8e'
dim-foreground = '#c2c2c68e'
dim-green = '#E163708e'
dim-magenta = '#FA857A8e'
dim-red = '#BA6D858e'
dim-white = '#E770848e'
dim-yellow = '#c2c2c68e'
light-black = '#AE5672'
light-blue = '#CA596B'
light-cyan = '#E16370'
light-foreground = '#FA857A'
light-green = '#BA6D85'
light-magenta = '#E77084'
light-red = '#c2c2c6'
light-white = '#AE5672'
light-yellow = '#CA596B'
