--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/argee/Pictures/Wallpapers/127440533_p0_master1200.jpg"

-- Special
background="#0c0c1b"
foreground="#c2c2c6"
cursor="#c2c2c6"

-- Colors
color0="#0c0c1b"
color1="#AE5672"
color2="#CA596B"
color3="#E16370"
color4="#FA857A"
color5="#BA6D85"
color6="#E77084"
color7="#c2c2c6"
color8="#5b5b6f"
color9="#AE5672"
color10="#CA596B"
color11="#E16370"
color12="#FA857A"
color13="#BA6D85"
color14="#E77084"
color15="#c2c2c6"
