# Shell variables
# Generated by 'wal'
wallpaper="/home/argee/Pictures/Wallpapers/127440533_p0_master1200.jpg"

# Special
background='#0c0c1b'
foreground='#c2c2c6'
cursor='#c2c2c6'

# Colors
color0='#0c0c1b'
color1='#AE5672'
color2='#CA596B'
color3='#E16370'
color4='#FA857A'
color5='#BA6D85'
color6='#E77084'
color7='#c2c2c6'
color8='#5b5b6f'
color9='#AE5672'
color10='#CA596B'
color11='#E16370'
color12='#FA857A'
color13='#BA6D85'
color14='#E77084'
color15='#c2c2c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
