[colors.primary]
background = "#0c0c1b"
foreground = "#c2c2c6"

[colors.cursor]
text = "#0c0c1b"
cursor = "#c2c2c6"

[colors.vi_mode_cursor]
text = "#0c0c1b"
cursor = "#c2c2c6"

[colors.search.matches]
foreground = "#0c0c1b"
background = "#c2c2c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5b5b6f"
background = "#c2c2c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0c0c1b"
red = "#AE5672"
green = "#CA596B"
yellow = "#E16370"
blue = "#FA857A"
magenta = "#BA6D85"
cyan = "#E77084"
white = "#c2c2c6"

[colors.bright]
black = "#5b5b6f"
red = "#AE5672"
green = "#CA596B"
yellow = "#E16370"
blue = "#FA857A"
magenta = "#BA6D85"
cyan = "#E77084"
white = "#c2c2c6"

[colors.dim]
black = "#c2c2c6"
red = "#AE5672"
green = "#BA6D85"
yellow = "#E16370"
blue = "#FA857A"
magenta = "#CA596B"
cyan = "#E77084"
white = "#5b5b6f"

